var datesWithDay = [
    {id:1, day: 'Monday', name: '12', type: 'AM'},
    {id:2, day: 'Monday', name: '01', type: 'AM'},
    {id:3, day: 'Monday', name: '02', type: 'AM'},
    {id:4, day: 'Monday', name: '03', type: 'AM'},
    {id:5, day: 'Monday', name: '04', type: 'AM'},
    {id:6, day: 'Monday', name: '05', type: 'AM'},
    {id:7, day: 'Monday', name: '06', type: 'AM'},
    {id:8, day: 'Monday', name: '07', type: 'AM'},
    {id:9, day: 'Monday', name: '08', type: 'AM'},
    {id:10, day: 'Monday', name: '09', type: 'AM'},
    {id:11, day: 'Monday', name: '10', type: 'AM'},
    {id:12, day: 'Monday', name: '11', type: 'AM'},
    {id:13, day: 'Monday', name: '12', type: 'PM'},
    {id:14, day: 'Monday', name: '01', type: 'PM'},
    {id:15, day: 'Monday', name: '02', type: 'PM'},
    {id:16, day: 'Monday', name: '03', type: 'PM'},
    {id:17, day: 'Monday', name: '04', type: 'PM'},
    {id:18, day: 'Monday', name: '05', type: 'PM'},
    {id:19, day: 'Monday', name: '06', type: 'PM'},
    {id:20, day: 'Monday', name: '07', type: 'PM'},
    {id:21, day: 'Monday', name: '08', type: 'PM'},
    {id:22, day: 'Monday', name: '09', type: 'PM'},
    {id:23, day: 'Monday', name: '10', type: 'PM'},
    {id:24, day: 'Monday', name: '11', type: 'PM'},

    {id:1, day: 'Tuesday', name: '12', type: 'AM'},
    {id:2, day: 'Tuesday', name: '01', type: 'AM'},
    {id:3, day: 'Tuesday', name: '02', type: 'AM'},
    {id:4, day: 'Tuesday', name: '03', type: 'AM'},
    {id:5, day: 'Tuesday', name: '04', type: 'AM'},
    {id:6, day: 'Tuesday', name: '05', type: 'AM'},
    {id:7, day: 'Tuesday', name: '06', type: 'AM'},
    {id:8, day: 'Tuesday', name: '07', type: 'AM'},
    {id:9, day: 'Tuesday', name: '08', type: 'AM'},
    {id:10, day: 'Tuesday', name: '09', type: 'AM'},
    {id:11, day: 'Tuesday', name: '10', type: 'AM'},
    {id:12, day: 'Tuesday', name: '11', type: 'AM'},
    {id:13, day: 'Tuesday', name: '12', type: 'PM'},
    {id:14, day: 'Tuesday', name: '01', type: 'PM'},
    {id:15, day: 'Tuesday', name: '02', type: 'PM'},
    {id:16, day: 'Tuesday', name: '03', type: 'PM'},
    {id:17, day: 'Tuesday', name: '04', type: 'PM'},
    {id:18, day: 'Tuesday', name: '05', type: 'PM'},
    {id:19, day: 'Tuesday', name: '06', type: 'PM'},
    {id:20, day: 'Tuesday', name: '07', type: 'PM'},
    {id:21, day: 'Tuesday', name: '08', type: 'PM'},
    {id:22, day: 'Tuesday', name: '09', type: 'PM'},
    {id:23, day: 'Tuesday', name: '10', type: 'PM'},
    {id:24, day: 'Tuesday', name: '11', type: 'PM'},

    {id:1, day: 'Wednesday', name: '12', type: 'AM'},
    {id:2, day: 'Wednesday', name: '01', type: 'AM'},
    {id:3, day: 'Wednesday', name: '02', type: 'AM'},
    {id:4, day: 'Wednesday', name: '03', type: 'AM'},
    {id:5, day: 'Wednesday', name: '04', type: 'AM'},
    {id:6, day: 'Wednesday', name: '05', type: 'AM'},
    {id:7, day: 'Wednesday', name: '06', type: 'AM'},
    {id:8, day: 'Wednesday', name: '07', type: 'AM'},
    {id:9, day: 'Wednesday', name: '08', type: 'AM'},
    {id:10, day: 'Wednesday', name: '09', type: 'AM'},
    {id:11, day: 'Wednesday', name: '10', type: 'AM'},
    {id:12, day: 'Wednesday', name: '11', type: 'AM'},
    {id:13, day: 'Wednesday', name: '12', type: 'PM'},
    {id:14, day: 'Wednesday', name: '01', type: 'PM'},
    {id:15, day: 'Wednesday', name: '02', type: 'PM'},
    {id:16, day: 'Wednesday', name: '03', type: 'PM'},
    {id:17, day: 'Wednesday', name: '04', type: 'PM'},
    {id:18, day: 'Wednesday', name: '05', type: 'PM'},
    {id:19, day: 'Wednesday', name: '06', type: 'PM'},
    {id:20, day: 'Wednesday', name: '07', type: 'PM'},
    {id:21, day: 'Wednesday', name: '08', type: 'PM'},
    {id:22, day: 'Wednesday', name: '09', type: 'PM'},
    {id:23, day: 'Wednesday', name: '10', type: 'PM'},
    {id:24, day: 'Wednesday', name: '11', type: 'PM'},

    {id:1, day: 'Thursday', name: '12', type: 'AM'},
    {id:2, day: 'Thursday', name: '01', type: 'AM'},
    {id:3, day: 'Thursday', name: '02', type: 'AM'},
    {id:4, day: 'Thursday', name: '03', type: 'AM'},
    {id:5, day: 'Thursday', name: '04', type: 'AM'},
    {id:6, day: 'Thursday', name: '05', type: 'AM'},
    {id:7, day: 'Thursday', name: '06', type: 'AM'},
    {id:8, day: 'Thursday', name: '07', type: 'AM'},
    {id:9, day: 'Thursday', name: '08', type: 'AM'},
    {id:10, day: 'Thursday', name: '09', type: 'AM'},
    {id:11, day: 'Thursday', name: '10', type: 'AM'},
    {id:12, day: 'Thursday', name: '11', type: 'AM'},
    {id:13, day: 'Thursday', name: '12', type: 'PM'},
    {id:14, day: 'Thursday', name: '01', type: 'PM'},
    {id:15, day: 'Thursday', name: '02', type: 'PM'},
    {id:16, day: 'Thursday', name: '03', type: 'PM'},
    {id:17, day: 'Thursday', name: '04', type: 'PM'},
    {id:18, day: 'Thursday', name: '05', type: 'PM'},
    {id:19, day: 'Thursday', name: '06', type: 'PM'},
    {id:20, day: 'Thursday', name: '07', type: 'PM'},
    {id:21, day: 'Thursday', name: '08', type: 'PM'},
    {id:22, day: 'Thursday', name: '09', type: 'PM'},
    {id:23, day: 'Thursday', name: '10', type: 'PM'},
    {id:24, day: 'Thursday', name: '11', type: 'PM'},

    {id:1, day: 'Friday', name: '12', type: 'AM'},
    {id:2, day: 'Friday', name: '01', type: 'AM'},
    {id:3, day: 'Friday', name: '02', type: 'AM'},
    {id:4, day: 'Friday', name: '03', type: 'AM'},
    {id:5, day: 'Friday', name: '04', type: 'AM'},
    {id:6, day: 'Friday', name: '05', type: 'AM'},
    {id:7, day: 'Friday', name: '06', type: 'AM'},
    {id:8, day: 'Friday', name: '07', type: 'AM'},
    {id:9, day: 'Friday', name: '08', type: 'AM'},
    {id:10, day: 'Friday', name: '09', type: 'AM'},
    {id:11, day: 'Friday', name: '10', type: 'AM'},
    {id:12, day: 'Friday', name: '11', type: 'AM'},
    {id:13, day: 'Friday', name: '12', type: 'PM'},
    {id:14, day: 'Friday', name: '01', type: 'PM'},
    {id:15, day: 'Friday', name: '02', type: 'PM'},
    {id:16, day: 'Friday', name: '03', type: 'PM'},
    {id:17, day: 'Friday', name: '04', type: 'PM'},
    {id:18, day: 'Friday', name: '05', type: 'PM'},
    {id:19, day: 'Friday', name: '06', type: 'PM'},
    {id:20, day: 'Friday', name: '07', type: 'PM'},
    {id:21, day: 'Friday', name: '08', type: 'PM'},
    {id:22, day: 'Friday', name: '09', type: 'PM'},
    {id:23, day: 'Friday', name: '10', type: 'PM'},
    {id:24, day: 'Friday', name: '11', type: 'PM'},

    {id:1, day: 'Saturday', name: '12', type: 'AM'},
    {id:2, day: 'Saturday', name: '01', type: 'AM'},
    {id:3, day: 'Saturday', name: '02', type: 'AM'},
    {id:4, day: 'Saturday', name: '03', type: 'AM'},
    {id:5, day: 'Saturday', name: '04', type: 'AM'},
    {id:6, day: 'Saturday', name: '05', type: 'AM'},
    {id:7, day: 'Saturday', name: '06', type: 'AM'},
    {id:8, day: 'Saturday', name: '07', type: 'AM'},
    {id:9, day: 'Saturday', name: '08', type: 'AM'},
    {id:10, day: 'Saturday', name: '09', type: 'AM'},
    {id:11, day: 'Saturday', name: '10', type: 'AM'},
    {id:12, day: 'Saturday', name: '11', type: 'AM'},
    {id:13, day: 'Saturday', name: '12', type: 'PM'},
    {id:14, day: 'Saturday', name: '01', type: 'PM'},
    {id:15, day: 'Saturday', name: '02', type: 'PM'},
    {id:16, day: 'Saturday', name: '03', type: 'PM'},
    {id:17, day: 'Saturday', name: '04', type: 'PM'},
    {id:18, day: 'Saturday', name: '05', type: 'PM'},
    {id:19, day: 'Saturday', name: '06', type: 'PM'},
    {id:20, day: 'Saturday', name: '07', type: 'PM'},
    {id:21, day: 'Saturday', name: '08', type: 'PM'},
    {id:22, day: 'Saturday', name: '09', type: 'PM'},
    {id:23, day: 'Saturday', name: '10', type: 'PM'},
    {id:24, day: 'Saturday', name: '11', type: 'PM'},

    {id:1, day: 'Sunday', name: '12', type: 'AM'},
    {id:2, day: 'Sunday', name: '01', type: 'AM'},
    {id:3, day: 'Sunday', name: '02', type: 'AM'},
    {id:4, day: 'Sunday', name: '03', type: 'AM'},
    {id:5, day: 'Sunday', name: '04', type: 'AM'},
    {id:6, day: 'Sunday', name: '05', type: 'AM'},
    {id:7, day: 'Sunday', name: '06', type: 'AM'},
    {id:8, day: 'Sunday', name: '07', type: 'AM'},
    {id:9, day: 'Sunday', name: '08', type: 'AM'},
    {id:10, day: 'Sunday', name: '09', type: 'AM'},
    {id:11, day: 'Sunday', name: '10', type: 'AM'},
    {id:12, day: 'Sunday', name: '11', type: 'AM'},
    {id:13, day: 'Sunday', name: '12', type: 'PM'},
    {id:14, day: 'Sunday', name: '01', type: 'PM'},
    {id:15, day: 'Sunday', name: '02', type: 'PM'},
    {id:16, day: 'Sunday', name: '03', type: 'PM'},
    {id:17, day: 'Sunday', name: '04', type: 'PM'},
    {id:18, day: 'Sunday', name: '05', type: 'PM'},
    {id:19, day: 'Sunday', name: '06', type: 'PM'},
    {id:20, day: 'Sunday', name: '07', type: 'PM'},
    {id:21, day: 'Sunday', name: '08', type: 'PM'},
    {id:22, day: 'Sunday', name: '09', type: 'PM'},
    {id:23, day: 'Sunday', name: '10', type: 'PM'},
    {id:24, day: 'Sunday', name: '11', type: 'PM'},
  ]
var dates = [
  {
    id: 'monday',
    name: 'Monday',
    dates: [
      {id:1, name: '12', type: 'AM'},
      {id:2, name: '01', type: 'AM'},
      {id:3, name: '02', type: 'AM'},
      {id:4, name: '03', type: 'AM'},
      {id:5, name: '04', type: 'AM'},
      {id:6, name: '05', type: 'AM'},
      {id:7, name: '06', type: 'AM'},
      {id:8, name: '07', type: 'AM'},
      {id:9, name: '08', type: 'AM'},
      {id:10, name: '09', type: 'AM'},
      {id:11, name: '10', type: 'AM'},
      {id:12, name: '11', type: 'AM'},
      {id:13, name: '12', type: 'PM'},
      {id:14, name: '01', type: 'PM'},
      {id:15, name: '02', type: 'PM'},
      {id:16, name: '03', type: 'PM'},
      {id:17, name: '04', type: 'PM'},
      {id:18, name: '05', type: 'PM'},
      {id:19, name: '06', type: 'PM'},
      {id:20, name: '07', type: 'PM'},
      {id:21, name: '08', type: 'PM'},
      {id:22, name: '09', type: 'PM'},
      {id:23, name: '10', type: 'PM'},
      {id:24, name: '11', type: 'PM'},
    ]
  },
  {
    id: 'tuesday',
    name: 'Tuesday',
    dates: [
      {id:1, name: '12', type: 'AM'},
      {id:2, name: '01', type: 'AM'},
      {id:3, name: '02', type: 'AM'},
      {id:4, name: '03', type: 'AM'},
      {id:5, name: '04', type: 'AM'},
      {id:6, name: '05', type: 'AM'},
      {id:7, name: '06', type: 'AM'},
      {id:8, name: '07', type: 'AM'},
      {id:9, name: '08', type: 'AM'},
      {id:10, name: '09', type: 'AM'},
      {id:11, name: '10', type: 'AM'},
      {id:12, name: '11', type: 'AM'},
      {id:13, name: '12', type: 'PM'},
      {id:14, name: '01', type: 'PM'},
      {id:15, name: '02', type: 'PM'},
      {id:16, name: '03', type: 'PM'},
      {id:17, name: '04', type: 'PM'},
      {id:18, name: '05', type: 'PM'},
      {id:19, name: '06', type: 'PM'},
      {id:20, name: '07', type: 'PM'},
      {id:21, name: '08', type: 'PM'},
      {id:22, name: '09', type: 'PM'},
      {id:23, name: '10', type: 'PM'},
      {id:24, name: '11', type: 'PM'},
    ]
  },
  {
    id: 'wednesday',
    name: 'Wednesday',
    dates: [
      {id:1, name: '12', type: 'AM'},
      {id:2, name: '01', type: 'AM'},
      {id:3, name: '02', type: 'AM'},
      {id:4, name: '03', type: 'AM'},
      {id:5, name: '04', type: 'AM'},
      {id:6, name: '05', type: 'AM'},
      {id:7, name: '06', type: 'AM'},
      {id:8, name: '07', type: 'AM'},
      {id:9, name: '08', type: 'AM'},
      {id:10, name: '09', type: 'AM'},
      {id:11, name: '10', type: 'AM'},
      {id:12, name: '11', type: 'AM'},
      {id:13, name: '12', type: 'PM'},
      {id:14, name: '01', type: 'PM'},
      {id:15, name: '02', type: 'PM'},
      {id:16, name: '03', type: 'PM'},
      {id:17, name: '04', type: 'PM'},
      {id:18, name: '05', type: 'PM'},
      {id:19, name: '06', type: 'PM'},
      {id:20, name: '07', type: 'PM'},
      {id:21, name: '08', type: 'PM'},
      {id:22, name: '09', type: 'PM'},
      {id:23, name: '10', type: 'PM'},
      {id:24, name: '11', type: 'PM'},
    ]
  },
  {
    id: 'thursday',
    name: 'Thursday',
    dates: [
      {id:1, name: '12', type: 'AM'},
      {id:2, name: '01', type: 'AM'},
      {id:3, name: '02', type: 'AM'},
      {id:4, name: '03', type: 'AM'},
      {id:5, name: '04', type: 'AM'},
      {id:6, name: '05', type: 'AM'},
      {id:7, name: '06', type: 'AM'},
      {id:8, name: '07', type: 'AM'},
      {id:9, name: '08', type: 'AM'},
      {id:10, name: '09', type: 'AM'},
      {id:11, name: '10', type: 'AM'},
      {id:12, name: '11', type: 'AM'},
      {id:13, name: '12', type: 'PM'},
      {id:14, name: '01', type: 'PM'},
      {id:15, name: '02', type: 'PM'},
      {id:16, name: '03', type: 'PM'},
      {id:17, name: '04', type: 'PM'},
      {id:18, name: '05', type: 'PM'},
      {id:19, name: '06', type: 'PM'},
      {id:20, name: '07', type: 'PM'},
      {id:21, name: '08', type: 'PM'},
      {id:22, name: '09', type: 'PM'},
      {id:23, name: '10', type: 'PM'},
      {id:24, name: '11', type: 'PM'},
    ]
  },
  {
    id: 'friday',
    name: 'Friday',
    dates: [
      {id:1, name: '12', type: 'AM'},
      {id:2, name: '01', type: 'AM'},
      {id:3, name: '02', type: 'AM'},
      {id:4, name: '03', type: 'AM'},
      {id:5, name: '04', type: 'AM'},
      {id:6, name: '05', type: 'AM'},
      {id:7, name: '06', type: 'AM'},
      {id:8, name: '07', type: 'AM'},
      {id:9, name: '08', type: 'AM'},
      {id:10, name: '09', type: 'AM'},
      {id:11, name: '10', type: 'AM'},
      {id:12, name: '11', type: 'AM'},
      {id:13, name: '12', type: 'PM'},
      {id:14, name: '01', type: 'PM'},
      {id:15, name: '02', type: 'PM'},
      {id:16, name: '03', type: 'PM'},
      {id:17, name: '04', type: 'PM'},
      {id:18, name: '05', type: 'PM'},
      {id:19, name: '06', type: 'PM'},
      {id:20, name: '07', type: 'PM'},
      {id:21, name: '08', type: 'PM'},
      {id:22, name: '09', type: 'PM'},
      {id:23, name: '10', type: 'PM'},
      {id:24, name: '11', type: 'PM'},
    ]
  },
  {
    id: 'saturday',
    name: 'Saturday',
    dates: [
      {id:1, name: '12', type: 'AM'},
      {id:2, name: '01', type: 'AM'},
      {id:3, name: '02', type: 'AM'},
      {id:4, name: '03', type: 'AM'},
      {id:5, name: '04', type: 'AM'},
      {id:6, name: '05', type: 'AM'},
      {id:7, name: '06', type: 'AM'},
      {id:8, name: '07', type: 'AM'},
      {id:9, name: '08', type: 'AM'},
      {id:10, name: '09', type: 'AM'},
      {id:11, name: '10', type: 'AM'},
      {id:12, name: '11', type: 'AM'},
      {id:13, name: '12', type: 'PM'},
      {id:14, name: '01', type: 'PM'},
      {id:15, name: '02', type: 'PM'},
      {id:16, name: '03', type: 'PM'},
      {id:17, name: '04', type: 'PM'},
      {id:18, name: '05', type: 'PM'},
      {id:19, name: '06', type: 'PM'},
      {id:20, name: '07', type: 'PM'},
      {id:21, name: '08', type: 'PM'},
      {id:22, name: '09', type: 'PM'},
      {id:23, name: '10', type: 'PM'},
      {id:24, name: '11', type: 'PM'},
    ]
  },
  {
    id: 'sunday',
    name: 'Sunday',
    dates: [
      {id:1, name: '12', type: 'AM'},
      {id:2, name: '01', type: 'AM'},
      {id:3, name: '02', type: 'AM'},
      {id:4, name: '03', type: 'AM'},
      {id:5, name: '04', type: 'AM'},
      {id:6, name: '05', type: 'AM'},
      {id:7, name: '06', type: 'AM'},
      {id:8, name: '07', type: 'AM'},
      {id:9, name: '08', type: 'AM'},
      {id:10, name: '09', type: 'AM'},
      {id:11, name: '10', type: 'AM'},
      {id:12, name: '11', type: 'AM'},
      {id:13, name: '12', type: 'PM'},
      {id:14, name: '01', type: 'PM'},
      {id:15, name: '02', type: 'PM'},
      {id:16, name: '03', type: 'PM'},
      {id:17, name: '04', type: 'PM'},
      {id:18, name: '05', type: 'PM'},
      {id:19, name: '06', type: 'PM'},
      {id:20, name: '07', type: 'PM'},
      {id:21, name: '08', type: 'PM'},
      {id:22, name: '09', type: 'PM'},
      {id:23, name: '10', type: 'PM'},
      {id:24, name: '11', type: 'PM'},
    ]
  },
]

export default dates;
